# Generated by Django 5.0.4 on 2024-05-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
