# Generated by Django 5.0.6 on 2024-07-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp_tracker_app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exp_tracker_app.item')),
            ],
        ),
    ]
